# -*- coding: utf-8 -*-
"""recipe-polis2-statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/patcon/valency-anndata/blob/main/docs/notebooks/recipe-polis2-statements.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install --quiet \
#   "git+https://github.com/patcon/polis@package-commentgraph#subdirectory=delphi/umap_narrative/polismath_commentgraph" \
#   "git+https://github.com/patcon/valency-anndata@main"

import valency_anndata as val

adata = val.datasets.polis.load("https://pol.is/report/r7wehfsmutrwndviddnii")

with val.viz.schematic_diagram(diff_from=adata):
    val.tools.recipe_polis2_statements(adata)

val.viz.embedding(
    # Transpose .var and .obs axes for plotting
    adata.transpose(),
    basis="content_umap",
    color=["evoc_polis2_top", "moderation_state"],
)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install datamapplot

FAKE_RENDER_DATAMAPPLOT = True

if FAKE_RENDER_DATAMAPPLOT:
  from IPython.display import Image, display

  display(Image(url="https://i.imgur.com/CMiO6nu.png", width=800))

else:
  import datamapplot
  import numpy as np

  label_layers = adata.varm["evoc_polis2"].transpose()
  # Humanized cluster labels in layers (not real topics yet)
  label_layers_humanized = [
      [f"Zoom{zoom_level}:Group{group_id}" for group_id in row]
      for zoom_level, row in enumerate(reversed(label_layers), start=1)
  ]

  datamapplot.create_interactive_plot(
      adata.varm["content_umap"],
      *label_layers_humanized,
      title="Bowling Green 2050",
      sub_title=f"{adata.shape[1]} statements",
      hover_text=adata.var["content"],
      enable_search=True,
      darkmode=True,
      height=500,
      # Needed when there are too many statements.
      # See: https://github.com/TutteInstitute/datamapplot/pull/67
      palette_theta_range=np.pi/8,
  )